[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Jeremy Miller <jgmiller88@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.0" # for day2_part2
chrono = "0.4" # day4_part1
